apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  namespace: multicluster-mgmt-argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/tempwiggle/GitOps-For-Multi-Openshift-Cluster-Management.git 
      revision: HEAD
      directories:
      - path: operators/*
      - path: operators/subs-and-customresources/*
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: operators
      source:
        repoURL: https://github.com/tempwiggle/GitOps-For-Multi-Openshift-Cluster-Management.git 
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values-main-ocp.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy: 
        syncOptions:
          - CreateNamespace=true
      # Optional
      #        automated:
      #          prune: true
      #          selfHeal: true
      #        syncOptions:
      #        - Replace=true
